services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"

    gateway:
        container_name: lattice
        build:
            context: .
            dockerfile: Dockerfile
            platforms:
                - linux/amd64
        environment:
            - REDIS_URL=${REDIS_URL}
        ports:
            - 8080:8080
